spring:
  application:
    name: CashFlow
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5436/cashflow
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    database: POSTGRESQL
    open-in-view: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: true

  web:
    cors:
      mappings:
        "/**":
          #CORS
          #Atualmente liberando acesso para o front local (localhost: 3000)
          #em produção substituir pelo domínio real do frontend https://meusite não esquece e adiciona cors em produção
          allowed-origins: "http://localhost:3000"
          allowed-methods: "*"
          allowed-headers: "*"
          allow-credentials: true

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION:86400000}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG

server:
  error:
    include-message: never
    include-binding-errors: never

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    # essa url virara dado sensivel em produção
    url: jdbc:postgresql://meubanco:5436/cashflow
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  error:
    include-message: never